'use client';
import {useState} from 'react';
import {CheckCircle2,Cloud,ExternalLink,GitCommitHorizontal,ShieldCheck,WalletCards} from 'lucide-react';
import {useLedger} from '@/lib/ledger';
import deployment from '@/artifacts/deployment.json';
type Source={url:string;version:string;digest:string};
const initial:Source[]=[{url:'https://release.example.com/a.json',version:'version',digest:'digest'},{url:'https://mirror.example.net/b.json',version:'version',digest:'digest'},{url:'https://registry.example.org/c.json',version:'version',digest:'digest'}];
export default function Home(){const l=useLedger(deployment.address);const[id,setId]=useState('REL-2026-01');const[project,setProject]=useState('Aurora CLI');const[sources,setSources]=useState(initial);const[lookup,setLookup]=useState('REL-2026-01');const[record,setRecord]=useState<any>(null);const set=(i:number,k:keyof Source,v:string)=>setSources(s=>s.map((x,n)=>n===i?{...x,[k]:v}:x));
 async function register(){const body=JSON.stringify(sources.map(s=>({url:s.url,version_path:s.version.split('.').filter(Boolean),digest_path:s.digest.split('.').filter(Boolean)})));await l.write('register_release',[id,project,body],async()=>true)}
 async function attest(){await l.write('attest_release',[id],async()=>{const r=await l.read('get_release',[l.account,id]);setRecord(r);return r?.id===id.toUpperCase()})}
 async function read(){try{setRecord(await l.read('get_release',[l.account,lookup]))}catch{setRecord(null)}}
 return <main><header><div className="brand"><span className="beacon"><GitCommitHorizontal/></span><div><b>BuildBeacon</b><small>RELEASE ATTESTATION NETWORK</small></div></div><div className="network"><i/> STUDIONET</div><button className="wallet" onClick={l.connect}><WalletCards size={16}/>{l.account?l.account.slice(0,6)+'…'+l.account.slice(-4):'Connect wallet'}</button></header><section className="hero"><p className="eyebrow">ARTIFACT INTEGRITY / THREE-WAY QUORUM</p><h1>A release is ready<br/><em>when the evidence agrees.</em></h1><p className="intro">BuildBeacon turns public release manifests into an auditable attestation. Three independent hosts must publish the same version and digest before a release can carry a quorum-backed badge.</p><div className="hero-note"><Cloud/><strong>2 of 3</strong><span>minimum matching attestations</span></div></section><section className="builder"><div className="heading"><span>01</span><div><p className="eyebrow">RELEASE INTAKE</p><h2>Assemble an evidence beacon</h2><p>Each source must be HTTPS and live on a distinct hostname.</p></div></div><div className="fields"><label>RELEASE ID<input value={id} onChange={e=>setId(e.target.value)}/></label><label>PROJECT NAME<input value={project} onChange={e=>setProject(e.target.value)}/></label></div><div className="manifest">{sources.map((s,i)=><div className="source" key={i}><div className="source-top"><span>HOST {i+1}</span><CheckCircle2/></div><label>MANIFEST URL<input value={s.url} onChange={e=>set(i,'url',e.target.value)}/></label><label>VERSION JSON PATH<input value={s.version} onChange={e=>set(i,'version',e.target.value)}/></label><label>DIGEST JSON PATH<input value={s.digest} onChange={e=>set(i,'digest',e.target.value)}/></label></div>)}</div><div className="actions"><button onClick={register} disabled={!l.account||l.busy}>Register release <span>→</span></button><button onClick={attest} disabled={!l.account||l.busy}>Attest with quorum <ShieldCheck size={16}/></button></div><p className="status">{l.message||'Connect your wallet to create an owner-scoped release record.'}{l.hash&&<a href={'https://explorer-studio.genlayer.com/tx/'+l.hash} target="_blank">Transaction <ExternalLink size={13}/></a>}</p></section><section className="archive"><div><p className="eyebrow">PUBLIC RELEASE LEDGER</p><h2>Read an attestation</h2><p>Look up the final version, digest, and supporting observations.</p></div><div className="lookup"><input value={lookup} onChange={e=>setLookup(e.target.value)}/><button onClick={read}>Read release</button></div>{record?.id&&<div className="result"><div><small>ATTESTATION</small><strong>{record.status}</strong><p>{record.project} · support {record.support}/3</p></div><div><small>VERSION</small><b>{record.version||'Conflict'}</b></div><div><small>DIGEST</small><code>{record.digest||'No quorum digest'}</code></div></div>}</section><footer>BuildBeacon · public artifact quorum · {deployment.address.slice(0,10)}…</footer></main>}
